spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to FernandoBank cards related prod APIs "
  contactDetails:
    name: "Fernando Salas - Product Owner"
    email: "fernandosalas@gmail.com"
  onCallSupport:
    - (617) 432-2356
    - (936) 564-8721