build:
  version: "2.0"

cards:
  message: "Welcome to FernandoBank cards related QA APIs"
  contactDetails:
    name: "Ponky Salas - QA Lead"
    email: "ponkysalas@gmail.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267