build:
  version: "3.0"

loans:
  message: "Welcome to FernandoBank loans related local APIs"
  contactDetails:
    name: "Fernando Salas - Developer"
    email: "luisfernandosalas@gmail.com"
  onCallSupport:
    - (555)555-1234
    - (555)555-4321