build:
  version: "3.0"

cards:
  message: "Welcome to FernandoBank cards related local APIs "
  contactDetails:
    name: "Fernando Salas - Developer"
    email: "fernandosalas@gmail.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932

